<a href="https://colab.research.google.com/github/zynosx/Learning-testingML/blob/main/Testigncodes1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
b = {'babil','chiki','ritam','riya'}
c = {'babil','chiki'}

In [ ]:
b.intersection(c)

{'babil', 'chiki'}

In [1]:
import numpy as np
list1=[2,7,3,6]
list2=[6,23,8,3]
list3=[4,3,6,3]

In [ ]:
arr = np.array([list1,list2,list3])

In [ ]:
arr

array([[ 2,  7,  3,  6],
       [ 6, 23,  8,  3],
       [ 4,  3,  6,  3]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.reshape(4,3)

array([[ 2,  7,  3],
       [ 6,  6, 23],
       [ 8,  3,  4],
       [ 3,  6,  3]])

In [ ]:
arr

array([[ 2,  7,  3,  6],
       [ 6, 23,  8,  3],
       [ 4,  3,  6,  3]])

In [ ]:
np.linspace(1,10,100)

In [2]:
np.random.randint(50,90,10)

array([64, 78, 66, 73, 71, 54, 56, 74, 87, 77])