<a href="https://colab.research.google.com/github/zynosx/Learning-testingML/blob/main/Testigncodes1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
b = {'babil','chiki','ritam','riya'}
c = {'babil','chiki'}

In [ ]:
b.intersection(c)

{'babil', 'chiki'}

In [ ]:
import numpy as np
list1=[2,7,3,6]
list2=[6,23,8,3]
list3=[4,3,6,3]

In [ ]:
arr = np.array([list1,list2,list3])

In [ ]:
arr

array([[ 2,  7,  3,  6],
       [ 6, 23,  8,  3],
       [ 4,  3,  6,  3]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.reshape(4,3)

array([[ 2,  7,  3],
       [ 6,  6, 23],
       [ 8,  3,  4],
       [ 3,  6,  3]])

In [ ]:
arr

array([[ 2,  7,  3,  6],
       [ 6, 23,  8,  3],
       [ 4,  3,  6,  3]])

In [ ]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [ ]:
np.random.randint(50,2230,10)

array([2018, 1133,  942,  776, 1622,  650, 1297, 1692, 1924,  961])

In [ ]:
#thisis from soumyajjal

In [ ]:
#testing pytho

In [ ]:
a=10

In [ ]:
b=10
b+a

In [ ]:
a=20
a